ARGUMENT. DATETIME is broader: 1000-01-01-9999-12-01 , TIMSTAMP 1970-2038;
SELECT CURTIME();
SELECT CURDATE();
SELECT DAYOFWEEK(NOW());
SELECT DATE_FORMAT(CURDATE(), '%m/%d/%Y');
SELECT DATE_FORMAT(NOW(), '%M %D at %H:%i');

CREATE TABLE tweets (
content VARCHAR(50),
user_name VARCHAR(10) PRIMARY KEY NOT NULL,
time_created TIMESTAMP DEFAULT NOW()
);
